feat: tela-de-doacoes
Grupo-6-PI/Front-end-Aplicacao pull request #5
Opened 2024-08-13 23:26 UTC by BiaCavalcant

2024-08-14 12:21 UTC, DaviRdaSilva commented on css/all.css
O z-index do menu de acessibilidade já testaram em todas as telas que tem o menu?

2024-08-14 12:25 UTC, DaviRdaSilva requested changes
Só confirma o teste do Z-INDEX e tá show

2024-08-14 14:31 UTC, BiaCavalcant commented
> Só confirma o teste do Z-INDEX e tá show

Okay, mto obrigada 😀

2024-08-18 20:18 UTC, BiaCavalcant commented
@DaviRdaSilva Já revisei e tá funcionando....

2024-08-19 11:53 UTC, DaviRdaSilva approved these changes

2024-08-19 11:56 UTC, merged